-- Foosrater schema for Supabase / PostgreSQL

create table if not exists public.games (
    id bigint generated by default as identity primary key,
    league_name text not null,
    r1 text not null,
    r2 text not null default '',
    b1 text not null,
    b2 text not null default '',
    red_score smallint not null check (red_score >= 0),
    blue_score smallint not null check (blue_score >= 0),
    date_time timestamp without time zone not null,
    created_at timestamptz not null default now()
);

create index if not exists games_league_date_idx
    on public.games (league_name, date_time, id);
