#!/usr/bin/env python3
"""Convert one or more Foosrater CSV files to SQL INSERT statements.

Examples:
    python scripts/csv_to_sql.py data/hmt_2024.csv > supabase_import.sql
    python scripts/csv_to_sql.py data/*.csv > supabase_import.sql

The CSV filename (without .csv) becomes league_name.
Run supabase_schema.sql in Supabase before running the generated output.
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path
import sys


REQUIRED_COLUMNS = {
    "R1",
    "R2",
    "B1",
    "B2",
    "red_score",
    "blue_score",
    "date_time",
}


def sql_string(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def validate_score(value: str, column: str, source: Path, row_number: int) -> int:
    try:
        score = int(value)
    except ValueError as exc:
        raise ValueError(
            f"{source}: row {row_number}: {column} must be an integer, got {value!r}"
        ) from exc

    if score < 0:
        raise ValueError(
            f"{source}: row {row_number}: {column} must be >= 0, got {score}"
        )
    return score


def read_rows(source: Path):
    league_name = source.stem

    with source.open("r", newline="", encoding="utf-8-sig") as handle:
        reader = csv.DictReader(handle)
        columns = set(reader.fieldnames or [])
        missing = REQUIRED_COLUMNS - columns
        if missing:
            raise ValueError(
                f"{source}: missing required columns: {', '.join(sorted(missing))}"
            )

        for row_number, row in enumerate(reader, start=2):
            yield {
                "league_name": league_name,
                "r1": (row["R1"] or "").strip(),
                "r2": (row["R2"] or "").strip(),
                "b1": (row["B1"] or "").strip(),
                "b2": (row["B2"] or "").strip(),
                "red_score": validate_score(
                    row["red_score"], "red_score", source, row_number
                ),
                "blue_score": validate_score(
                    row["blue_score"], "blue_score", source, row_number
                ),
                "date_time": (row["date_time"] or "").strip(),
            }


def format_insert(row):
    return (
        "    ("
        f"{sql_string(row['league_name'])}, "
        f"{sql_string(row['r1'])}, "
        f"{sql_string(row['r2'])}, "
        f"{sql_string(row['b1'])}, "
        f"{sql_string(row['b2'])}, "
        f"{row['red_score']}, "
        f"{row['blue_score']}, "
        f"{sql_string(row['date_time'])}::timestamp"
        ")"
    )


def main():
    parser = argparse.ArgumentParser(
        description="Convert Foosrater CSV files to Supabase/Postgres INSERT SQL."
    )
    parser.add_argument(
        "csv_files",
        nargs="+",
        type=Path,
        help="CSV file(s); the filename stem becomes the league name.",
    )
    parser.add_argument(
        "--replace-leagues",
        action="store_true",
        help=(
            "Emit DELETE statements for the imported league names before INSERTs. "
            "Useful when re-running a migration."
        ),
    )
    args = parser.parse_args()

    rows = []
    for source in args.csv_files:
        if not source.is_file():
            parser.error(f"File not found: {source}")
        rows.extend(read_rows(source))

    if not rows:
        print("-- No game rows found.", file=sys.stdout)
        return

    leagues = sorted({row["league_name"] for row in rows})

    print("-- Generated by scripts/csv_to_sql.py")
    print("begin;")
    print()

    if args.replace_leagues:
        league_values = ", ".join(sql_string(name) for name in leagues)
        print(f"delete from public.games where league_name in ({league_values});")
        print()

    print(
        "insert into public.games "
        "(league_name, r1, r2, b1, b2, red_score, blue_score, date_time)"
    )
    print("values")
    print(",\n".join(format_insert(row) for row in rows) + ";")
    print()
    print("commit;")


if __name__ == "__main__":
    main()
